# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestPeopleCrud():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_people_crud(self, server):
        # url = url_for("index", _external=True)
        url = "http://localhost:5000"
        self.driver.get(url)
        self.driver.set_window_size(1050, 708)
        self.driver.find_element(By.LINK_TEXT, "+ Add").click()
        self.driver.find_element(By.ID, "personName").click()
        self.driver.find_element(By.ID, "personName").send_keys("test")
        self.driver.find_element(By.ID, "personAge").send_keys("20")
        self.driver.find_element(By.ID, "submitBtn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
        self.driver.find_element(By.ID, "personAge").click()
        self.driver.find_element(By.ID, "personAge").send_keys("30")
        self.driver.find_element(By.ID, "submitBtn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
