name: Codacy Coverage Reporter

on: [push]

jobs:
  build:
    uses: ./.github/workflows/python-package.yaml

  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter

    needs: build
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-result
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
