name: Code Coverage Reporter

on: [push, pull_request]

jobs:
  build:
    uses: ./.github/workflows/python-package.yaml

  codacy-reporter:
    runs-on: ubuntu-latest
    name: codacy-reporter

    needs: build
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-result
      - name: Upload coverage reports to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

  codecov-reporter:
    runs-on: ubuntu-latest
    name: codecov-reporter

    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-result
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  coveralls-reporter:
    runs-on: ubuntu-latest
    name: coveralls-reporter

    needs: build
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-result
      - name: Upload coverage reports to Coveralls
        uses: coverallsapp/github-action@v2
