name: Code Coverage Reporter
on: [push, pull_request]
jobs:
  build:
    name: Build and test
    outputs:
      previous-commit: ${{ steps.get-previous-commit.outputs.commit-hash }}
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15.3
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: (${{ github.ref }}) Download source code
        uses: actions/checkout@v3
        with:
          path: ./source
          fetch-depth: 0
      - name: (${{ github.ref }}) Build and test
        uses: ./source/.github/actions/build-and-test
        with:
          working-directory: ./source

      - name: (${{ github.base_ref }}) Download source code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: ./target
      - name: (${{ github.base_ref }}) Build and test
        if: github.event_name == 'pull_request'
        uses: ./source/.github/actions/build-and-test
        with:
          working-directory: ./target
          coverage-output: coverage-target

      - name: Get previous commit on branch
        id: get-previous-commit
        if: github.event_name == 'push'
        working-directory: ./source
        run: echo "commit-hash=$(git rev-parse HEAD~1)" >> $GITHUB_OUTPUT
      - name: (previous) Download source code
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-previous-commit.outputs.commit-hash }}
          path: ./previous
      - name: (previous) Build and test
        if: github.event_name == 'push'
        uses: ./source/.github/actions/build-and-test
        with:
          working-directory: ./previous
          coverage-output: coverage-previous

  coverage-for-commit:
    name: Create coverage report and annotations for commit
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: (${{ github.ref }}) Download source code
        uses: actions/checkout@v3
        with:
          path: ./source
      - name: (${{ github.ref }}) Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: (${{ needs.build.outputs.previous-commit }}) Download source code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.build.outputs.previous-commit }}
          path: ./previous
      - name: (${{ needs.build.outputs.previous-commit }}) Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-previous

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pycobertura
        run: |
          python -m pip install --upgrade pip
          pip install pycobertura
      - name: Annotate
        run: pycobertura show --format github-annotation coverage.xml | sed 's/notice/warning/g'
      - name: Generate comment markdown
        run: |
          touch comment.md
          echo "# Current coverage" >> comment.md
          pycobertura show --format markdown coverage.xml >> comment.md
          echo "# Previous coverage" >> comment.md
          pycobertura show --format markdown coverage-previous.xml >> comment.md
          echo "# Coverage diff report" >> comment.md
          pycobertura diff --format markdown coverage-previous.xml coverage.xml --source1 previous/ --source2 source/ >> comment.md
      - id: get-comment-body
        run: |
          body="$(cat comment.md)"
          delimiter="$(openssl rand -hex 8)"
          echo "body<<$delimiter" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
      - name: Add comment to commit
        uses: peter-evans/commit-comment@v2
        with:
          body: ${{ steps.get-comment-body.outputs.body }}

  coverage-for-pull-request:
    name: Create coverage report for pull request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pull-requests: write
    steps:
      - name: (${{ github.ref }}) Download source code
        uses: actions/checkout@v3
        with:
          path: ./source
      - name: (${{ github.ref }}) Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: (${{ github.base_ref }}) Download source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: ./target
      - name: (${{ github.base_ref }}) Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-target

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pycobertura
        run: |
          python -m pip install --upgrade pip
          pip install pycobertura
      - name: Generate comment markdown
        env:
          SOURCE: ${{ github.head_ref }}
          TARGET: ${{ github.base_ref }}
        run: |
          touch comment.md
          echo "# Source branch coverage ($SOURCE)" >> comment.md
          pycobertura show --format markdown coverage.xml >> comment.md
          echo "# Target branch coverage ($TARGET)" >> comment.md
          pycobertura show --format markdown coverage-target.xml >> comment.md
          echo "# Coverage diff report" >> comment.md
          pycobertura diff --format markdown coverage-target.xml coverage.xml --source1 target/ --source2 source/ >> comment.md
          cat comment.md
      - name: Add comment to pull request
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: comment.md
  # build:
  #   uses: ./.github/workflows/python-package.yaml
  #
  # codacy-reporter:
  #   runs-on: ubuntu-latest
  #   name: codacy-reporter
  #
  #   needs: build
  #   steps:
  #     - name: Download coverage report
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: coverage-result
  #     - name: Upload coverage reports to Codacy
  #       uses: codacy/codacy-coverage-reporter-action@v1
  #       with:
  #         project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  #         coverage-reports: coverage.xml
  #
  # codecov-reporter:
  #   runs-on: ubuntu-latest
  #   name: codecov-reporter
  #
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Download coverage report
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: coverage-result
  #     - name: Upload coverage reports to Codecov
  #       uses: codecov/codecov-action@v3
  #       env:
  #         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  #
  # coveralls-reporter:
  #   runs-on: ubuntu-latest
  #   name: coveralls-reporter
  #
  #   needs: build
  #   steps:
  #     - name: Download coverage report
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: coverage-result
  #     - name: Upload coverage reports to Coveralls
  #       uses: coverallsapp/github-action@v2
